apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: workerservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: workerservice
        image: {acr-prefix}.azurecr.io/workerservice:latest
        resources:
          limits:
            cpu: "20m"
            memory: "55M"